program ClienteDesktopPousada;

uses
  System.StartUpCopy,
  FMX.Forms,
  desktop.infra.styles in 'infra\styles\desktop.infra.styles.pas' {ViewStyles},
  desktop.views.principal in 'views\desktop.views.principal.pas' {ViewPrincipal},
  cliente.infra.repository.base.crud.interfaces in 'infra\repository\cliente.infra.repository.base.crud.interfaces.pas',
  shared.json in '..\..\shared\shared.json.pas',
  cliente.infra.conexao.interfaces in 'infra\conexao\cliente.infra.conexao.interfaces.pas',
  cliente.infra.repository.produtos.interfaces in 'infra\repository\cliente.infra.repository.produtos.interfaces.pas',
  entidades.clientes in '..\..\entidades\entidades.clientes.pas',
  entidades.contatos in '..\..\entidades\entidades.contatos.pas',
  entidades.empresa.contatos in '..\..\entidades\entidades.empresa.contatos.pas',
  entidades.empresa.endereco in '..\..\entidades\entidades.empresa.endereco.pas',
  entidades.empresa in '..\..\entidades\entidades.empresa.pas',
  entidades.endereco in '..\..\entidades\entidades.endereco.pas',
  entidades.estadia.acompanhante in '..\..\entidades\entidades.estadia.acompanhante.pas',
  entidades.estadia in '..\..\entidades\entidades.estadia.pas',
  entidades.grupoprodutos in '..\..\entidades\entidades.grupoprodutos.pas',
  entidades.pessoa in '..\..\entidades\entidades.pessoa.pas',
  entidades.produtos in '..\..\entidades\entidades.produtos.pas',
  entidades.unidadehabitacional.caracteristicas in '..\..\entidades\entidades.unidadehabitacional.caracteristicas.pas',
  entidades.unidadehabitacional.categoria in '..\..\entidades\entidades.unidadehabitacional.categoria.pas',
  entidades.unidadehabitacional in '..\..\entidades\entidades.unidadehabitacional.pas',
  entidades.usuario in '..\..\entidades\entidades.usuario.pas',
  cliente.infra.repository.produtos in 'infra\repository\cliente.infra.repository.produtos.pas',
  validador.interfaces in '..\..\validador\validador.interfaces.pas',
  validador in '..\..\validador\validador.pas',
  validador.validacoessimples in '..\..\validador\validador.validacoessimples.pas',
  entidades.produtos.validacoes.basicas in '..\..\entidades\validacoes\entidades.produtos.validacoes.basicas.pas',
  cliente.model.base in 'model\cliente.model.base.pas',
  cliente.model.produtos in 'model\cliente.model.produtos.pas',
  desktop.views.base in 'views\desktop.views.base.pas' {ViewBase},
  cliente.infra.routes in 'infra\routes\cliente.infra.routes.pas',
  cliente.presenter.produtos.interfaces in 'presenters\cliente.presenter.produtos.interfaces.pas',
  cliente.presenter.produtos in 'presenters\cliente.presenter.produtos.pas',
  cliente.infra.conexao in 'infra\conexao\cliente.infra.conexao.pas',
  cliente.infra.binds in 'infra\binds\cliente.infra.binds.pas',
  cliente.model.grupos.produtos in 'model\cliente.model.grupos.produtos.pas',
  cliente.infra.repository.grupos.produtos.interfaces in 'infra\repository\cliente.infra.repository.grupos.produtos.interfaces.pas',
  cliente.infra.repository.grupos.produtos in 'infra\repository\cliente.infra.repository.grupos.produtos.pas',
  entidades.grupos.produtos.validacoes.basicas in '..\..\entidades\validacoes\entidades.grupos.produtos.validacoes.basicas.pas',
  cliente.presenter.grupos.produtos in 'presenters\cliente.presenter.grupos.produtos.pas',
  cliente.presenter.grupos.produtos.interfaces in 'presenters\cliente.presenter.grupos.produtos.interfaces.pas',
  desktop.views.base.cadastro in 'views\desktop.views.base.cadastro.pas' {ViewBaseCadastro},
  desktop.views.grupos.produtos in 'views\desktop.views.grupos.produtos.pas' {ViewGrupoProdutos},
  desktop.views.produtos in 'views\desktop.views.produtos.pas' {ViewProdutos},
  desktop.views.messagebox in 'views\desktop.views.messagebox.pas' {MessageBox},
  shared.exceptions in '..\..\shared\shared.exceptions.pas',
  cliente.infra.repository.unidadehabitacional.caracteristicas.interfaces in 'infra\repository\cliente.infra.repository.unidadehabitacional.caracteristicas.interfaces.pas',
  cliente.infra.repository.unidadehabitacional.caracteristicas in 'infra\repository\cliente.infra.repository.unidadehabitacional.caracteristicas.pas',
  entidades.caracteristicas in '..\..\entidades\entidades.caracteristicas.pas',
  entidades.caracteristicas.validacoes.basicas in '..\..\entidades\validacoes\entidades.caracteristicas.validacoes.basicas.pas',
  cliente.infra.repository.caracteristicas.interfaces in 'infra\repository\cliente.infra.repository.caracteristicas.interfaces.pas',
  cliente.infra.repository.caracteristicas in 'infra\repository\cliente.infra.repository.caracteristicas.pas',
  cliente.model.caracteristicas in 'model\cliente.model.caracteristicas.pas',
  cliente.presenter.caracteristicas.interfaces in 'presenters\cliente.presenter.caracteristicas.interfaces.pas',
  cliente.presenter.caracteristicas in 'presenters\cliente.presenter.caracteristicas.pas',
  desktop.views.caracteristicas in 'views\desktop.views.caracteristicas.pas' {ViewCaracteristicas},
  desktop.views.inicio in 'views\desktop.views.inicio.pas' {ViewInicio},
  desktop.views.empresa in 'views\desktop.views.empresa.pas' {ViewEmpresas},
  desktop.views.login in 'views\desktop.views.login.pas' {ViewLogin},
  cliente.infra.repository.usuarios.interfaces in 'infra\repository\cliente.infra.repository.usuarios.interfaces.pas',
  cliente.infra.repository.usuarios in 'infra\repository\cliente.infra.repository.usuarios.pas',
  cliente.model.usuarios in 'model\cliente.model.usuarios.pas',
  entidades.usuarios.validacoes.basicas in '..\..\entidades\validacoes\entidades.usuarios.validacoes.basicas.pas',
  cliente.presenter.usuarios in 'presenters\cliente.presenter.usuarios.pas',
  cliente.presenter.usuarios.interfaces in 'presenters\cliente.presenter.usuarios.interfaces.pas',
  desktop.views.usuario in 'views\desktop.views.usuario.pas' {ViewUsuarios},
  cliente.infra.repository.empresas.interfaces in 'infra\repository\cliente.infra.repository.empresas.interfaces.pas',
  cliente.infra.repository.empresas in 'infra\repository\cliente.infra.repository.empresas.pas',
  cliente.model.empresas in 'model\cliente.model.empresas.pas',
  entidades.empresas.validacoes.basicas in '..\..\entidades\validacoes\entidades.empresas.validacoes.basicas.pas',
  cliente.presenter.empresas in 'presenters\cliente.presenter.empresas.pas',
  cliente.presenter.empresas.interfaces in 'presenters\cliente.presenter.empresas.interfaces.pas',
  cliente.infra.repository.unidadehabitacional.interfaces in 'infra\repository\cliente.infra.repository.unidadehabitacional.interfaces.pas',
  cliente.infra.repository.unidadehabitacional in 'infra\repository\cliente.infra.repository.unidadehabitacional.pas',
  cliente.model.unidadeshabitacionais in 'model\cliente.model.unidadeshabitacionais.pas',
  entidades.unidadehabitacional.validacoes.base in '..\..\entidades\validacoes\entidades.unidadehabitacional.validacoes.base.pas',
  cliente.presenter.unidadeshabitacionais.interfaces in 'presenters\cliente.presenter.unidadeshabitacionais.interfaces.pas',
  cliente.presenter.unidadeshabitacionais in 'presenters\cliente.presenter.unidadeshabitacionais.pas',
  desktop.views.unidadeshabitacionais in 'views\desktop.views.unidadeshabitacionais.pas' {ViewUnidadesHabitacionais},
  cliente.infra.repository.unidadehabitacional.categorias.interfaces in 'infra\repository\cliente.infra.repository.unidadehabitacional.categorias.interfaces.pas',
  cliente.infra.repository.unidadehabitacional.categorias in 'infra\repository\cliente.infra.repository.unidadehabitacional.categorias.pas',
  desktop.views.unidadeshabitacionais.categorias in 'views\desktop.views.unidadeshabitacionais.categorias.pas' {ViewUnidadesHabitacionaisCategorias};

{$R *.res}

begin
  ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;

  Application.CreateForm(TViewLogin, ViewLogin);
  Application.CreateForm(TViewStyles, ViewStyles);
  Application.CreateForm(TViewPrincipal, ViewPrincipal);
  Application.CreateForm(TViewUsuarios, ViewUsuarios);
  Application.CreateForm(TViewUnidadesHabitacionais, ViewUnidadesHabitacionais);
  Application.CreateForm(TViewUnidadesHabitacionaisCategorias, ViewUnidadesHabitacionaisCategorias);
  Application.Run;
end.
